In [69]:
import numpy as np

In [70]:
a=np.array([[3,1,4],[9,4,5],[9,4,6]])
b=np.array([3,6,9])

In [71]:
d=np.linalg.det(a)
d

2.9999999999999996

Determinant of a!=0 Hence, Inverse Exist. Rank(A)=3 Rank(AB)=3, Hence has a Solution.

In [72]:
x=np.linalg.solve(a,b)
x

array([-9., 18.,  3.])

In [73]:
a=np.array([[2,4,6,8],[6,6,8,8]])
a

array([[2, 4, 6, 8],
       [6, 6, 8, 8]])

In [74]:
a[0]=a[0]-a[0].mean()
a[1]=a[1]-a[1].mean()
#centered data in each row in matrix A
a

array([[-3, -1,  1,  3],
       [-1, -1,  1,  1]])

In [75]:
# Co-Variance Matrix
C=np.matmul(a,a.T)
C

array([[20,  8],
       [ 8,  4]])

In [76]:
Values,Vectors=np.linalg.eig(C)
print(f'Values: {Values}\nVectors: {Vectors}')

Values: [23.3137085  0.6862915]
Vectors: [[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


In [77]:
# First Principle component is of Large value of eigen Value
First_PC=Vectors[:,0]
First_PC

array([0.92387953, 0.38268343])

In [78]:
# Reduced Data Matrix
np.matmul(First_PC,a)

array([-3.15432203, -1.30656296,  1.30656296,  3.15432203])