In [22]:
!pip install loess
from loess.loess_2d import loess_2d as l2
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression as l

In [23]:
Z=[1,0,1,4,3,2,5,6,9,13,15,16]
z=np.array(Z)

In [24]:
X=[[1,1],
[2,1],
[2,2],
[3,2],
[5,4],
[5,6],
[6,5],
[7,4],
[10,8],
[11,7],
[11,9],
[12,10]]

In [25]:
X1=pd.DataFrame(X)
x=X1.iloc[0:13][0].values
y=X1.iloc[0:13][1].values

In [26]:
#from skmisc import loess
from skmisc.loess import loess

WLS by following Variance formula in the Link Below link
https://math.stackexchange.com/questions/3997343/how-to-calculate-the-variance-of-the-error-term-in-least-squares-method-for-simp

In [27]:
lm=loess(X,Z,degree=2,span=0.9)
lm.fit()
SZ=lm.predict(X)
sz=SZ.values
sz

array([ 0.15816794,  1.26175196,  4.76667098,  3.53781019,  3.2108452 ,
        2.32615925,  6.7806428 ,  4.76667098, 11.30364892, 12.66442148,
       12.86530323, 16.48432032])

In [28]:
dfz=pd.DataFrame(sz)
pro=dfz.describe()
std=pro.loc['std']
var=std**2
var

0    28.332893
Name: std, dtype: float64

In [29]:
n=len(sz)
mean = sum(sz)/n
SSX=sum((j - mean) ** 2 for j in sz)
variance = SSX/(n - 1)
vari=[]

In [30]:
variance

28.332892715855007

In [31]:
for i in sz:
    print(variance*(1-1/n-(i - mean) ** 2/SSX))
    vari.append(variance*(1-1/n-(i - mean) ** 2/SSX))
w=1/np.array(vari)
w

22.108382559942395
23.305719285183606
25.639988746610513
25.075838748229184
24.879488936503233
24.250766937309322
25.970845578856284
25.639988746610513
24.02599838042832
22.71301761305012
22.490672148954683
17.228219476871885


array([0.04523171, 0.04290792, 0.03900158, 0.03987902, 0.04019375,
       0.04123581, 0.03850471, 0.03900158, 0.04162158, 0.04402762,
       0.04446288, 0.0580443 ])

In [32]:
lr=l()
lr.fit(X,Z,w)
lr.score(X,Z,w)

0.9105551257542451

In [33]:
# Using Vector_2d function
f, w = l2(x,y,z,degree=2,frac=0.9)
w

array([9.65088209e-01, 9.57990448e-01, 9.71067072e-01, 5.13444002e-04,
       8.67004370e-01, 9.99960021e-01, 9.75107276e-01, 9.98419812e-01,
       7.05988023e-01, 9.99733809e-01, 6.53100372e-01, 9.81682826e-01])

In [34]:
f

array([ 0.68788848,  0.17014385,  1.27703405,  1.20017764,  3.54770212,
        2.02871299,  4.4001736 ,  6.1186468 , 10.55999884, 12.95259598,
       13.17149626, 16.39613027])

Weighted Linear Regression

In [35]:
lr=l()
lr.fit(X,Z,w)
r=lr.score(X,Z,w)
print(f'R2 of WLS: {r}')
y_w=lr.predict(X)
y_w=pd.DataFrame(y_w)
pro=y_w.describe()

R2 of WLS: 0.9206028948204623


In [36]:
#Standard Error
std=pro.loc['std']
e=std/n**(1/2)
print(f'Standard Error of WLS: {e}')

Standard Error of WLS: 0    1.601902
Name: std, dtype: float64


In [37]:
#adjusted R-square
print(f'adjusted R-square of WLS: {1-(1-r)*(n-1)/(n-2-1)}')

adjusted R-square of WLS: 0.9029590936694539


Linear Regression

In [38]:
#R2 Value
lr=l()
lr.fit(X,Z)
r=lr.score(X,Z)
print(f'R2 of OLS: {r}')
y_o=lr.predict(X)
y_o=pd.DataFrame(y_o)
pro=y_o.describe()

R2 of OLS: 0.903737802561535


In [39]:
#Standard Error
std=pro.loc['std']
e=std/len(y_w)**(1/2)
print(f'Standard Error of OLS: {e}')

Standard Error of OLS: 0    1.557361
Name: std, dtype: float64


In [40]:
#adjusted R-square
print(f'adjusted R-square of OLS: {1-(1-r)*(n-1)/(n-2-1)}')

adjusted R-square of OLS: 0.8823462031307651


In [41]:
# Trying for more than two features whether the skmisc will work or not.
X1=[[1,1,1],
[2,1,1],
[2,2,2],
[3,2,3],
[5,4,4],
[5,6,5],
[6,5,6],
[7,4,7],
[10,8,1],
[11,7,1],
[11,9,2],
[12,10,2]]
lm=loess(X1,Z,degree=2,span=0.9)
lm.fit()
SZ=lm.predict(X)
sz=SZ.values
sz
#Even LOESS in skmisc also doesn't support more than two features.

ValueError: b'Chernobyl! trL>n 14.01'

In [42]:
d=np.transpose(X)
d

array([[ 1,  2,  2,  3,  5,  5,  6,  7, 10, 11, 11, 12],
       [ 1,  1,  2,  2,  4,  6,  5,  4,  8,  7,  9, 10]])

Covariance Matrix

In [43]:
cov_matrix = np.cov(d)
cov_matrix

array([[15.47727273, 11.65909091],
       [11.65909091,  9.71969697]])